/** Tushare Pro 接口名 */
export enum TushareApiName {
  STOCK_BASIC = 'stock_basic',
  STOCK_COMPANY = 'stock_company',
  TRADE_CAL = 'trade_cal',
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
  ADJ_FACTOR = 'adj_factor',
  DAILY_BASIC = 'daily_basic',
  INDEX_DAILY = 'index_daily',
  MONEYFLOW_DC = 'moneyflow',
  MONEYFLOW_IND_DC = 'moneyflow_ind_dc',
  MONEYFLOW_MKT_DC = 'moneyflow_mkt_dc',
  MONEYFLOW_HSGT = 'moneyflow_hsgt',
  INCOME = 'income',
  BALANCE_SHEET = 'balancesheet',
  CASHFLOW = 'cashflow',
  EXPRESS = 'express',
  FINA_INDICATOR = 'fina_indicator',
  DIVIDEND = 'dividend',
  TOP10_HOLDERS = 'top10_holders',
  TOP10_FLOAT_HOLDERS = 'top10_floatholders',
  STK_LIMIT = 'stk_limit',
  SUSPEND_D = 'suspend_d',
  INDEX_WEIGHT = 'index_weight',
  TOP_LIST = 'top_list',
  TOP_INST = 'top_inst',
  BLOCK_TRADE = 'block_trade',
  SHARE_FLOAT = 'share_float',
  FORECAST = 'forecast_vip',
  STK_HOLDER_NUMBER = 'stk_holdernumber',
  HK_HOLD = 'hk_hold',
  INDEX_DAILY_BASIC = 'index_dailybasic',
  STK_HOLDER_TRADE = 'stk_holdertrade',
  PLEDGE_STAT = 'pledge_stat',
  FINA_AUDIT = 'fina_audit',
  DISCLOSURE_DATE = 'disclosure_date',
  FINA_MAINBZ = 'fina_mainbz',
  INDEX_CLASSIFY = 'index_classify',
  INDEX_MEMBER_ALL = 'index_member_all',
  REPURCHASE = 'repurchase',
  CB_BASIC = 'cb_basic',
  CB_DAILY = 'cb_daily',
}

/** A 股常用交易所代码 */
export enum StockExchange {
  SSE = 'SSE',
  SZSE = 'SZSE',
  BSE = 'BSE',
  HKEX = 'HKEX',
}

/** 股票上市状态 */
export enum StockListStatus {
  LISTED = 'L',
  DELISTED = 'D',
  PAUSED = 'P',
}

/** 交易日历开闭市状态 */
export enum TradeCalendarOpenStatus {
  CLOSED = '0',
  OPEN = '1',
}

/** 东财板块资金流向分类 */
export enum MoneyflowContentType {
  INDUSTRY = '行业',
  CONCEPT = '概念',
  REGION = '地域',
}

/** 同步任务枚举，需与 Prisma Schema 中的 TushareSyncTask 保持一致 */
export enum TushareSyncTaskName {
  STOCK_BASIC = 'STOCK_BASIC',
  STOCK_COMPANY = 'STOCK_COMPANY',
  TRADE_CAL = 'TRADE_CAL',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  ADJ_FACTOR = 'ADJ_FACTOR',
  DAILY_BASIC = 'DAILY_BASIC',
  INDEX_DAILY = 'INDEX_DAILY',
  MONEYFLOW_DC = 'MONEYFLOW_DC',
  MONEYFLOW_IND_DC = 'MONEYFLOW_IND_DC',
  MONEYFLOW_MKT_DC = 'MONEYFLOW_MKT_DC',
  MONEYFLOW_HSGT = 'MONEYFLOW_HSGT',
  INCOME = 'INCOME',
  BALANCE_SHEET = 'BALANCE_SHEET',
  CASHFLOW = 'CASHFLOW',
  EXPRESS = 'EXPRESS',
  FINA_INDICATOR = 'FINA_INDICATOR',
  DIVIDEND = 'DIVIDEND',
  TOP10_HOLDERS = 'TOP10_HOLDERS',
  TOP10_FLOAT_HOLDERS = 'TOP10_FLOAT_HOLDERS',
  STK_LIMIT = 'STK_LIMIT',
  SUSPEND_D = 'SUSPEND_D',
  INDEX_WEIGHT = 'INDEX_WEIGHT',
  MARGIN_DETAIL = 'MARGIN_DETAIL',
  TOP_LIST = 'TOP_LIST',
  TOP_INST = 'TOP_INST',
  BLOCK_TRADE = 'BLOCK_TRADE',
  SHARE_FLOAT = 'SHARE_FLOAT',
  DATA_QUALITY_CHECK = 'DATA_QUALITY_CHECK',
  FORECAST = 'FORECAST',
  STK_HOLDER_NUMBER = 'STK_HOLDER_NUMBER',
  HK_HOLD = 'HK_HOLD',
  INDEX_DAILY_BASIC = 'INDEX_DAILY_BASIC',
  STK_HOLDER_TRADE = 'STK_HOLDER_TRADE',
  PLEDGE_STAT = 'PLEDGE_STAT',
  FINA_AUDIT = 'FINA_AUDIT',
  DISCLOSURE_DATE = 'DISCLOSURE_DATE',
  FINA_MAINBZ = 'FINA_MAINBZ',
  INDEX_CLASSIFY = 'INDEX_CLASSIFY',
  INDEX_MEMBER_ALL = 'INDEX_MEMBER_ALL',
  REPURCHASE = 'REPURCHASE',
  CB_BASIC = 'CB_BASIC',
  CB_DAILY = 'CB_DAILY',
}

/** 同步执行状态 */
export enum TushareSyncExecutionStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

/** 每日盘后同步时间：18:30（上海时区） */
export const TUSHARE_SYNC_CRON = '0 30 18 * * *'
export const TUSHARE_SYNC_TIME_ZONE = 'Asia/Shanghai'
export const TUSHARE_SYNC_CUTOFF_HOUR = 18
export const TUSHARE_SYNC_CUTOFF_MINUTE = 30

/** 历史补数默认起点，可通过环境变量覆盖 */
export const TUSHARE_DEFAULT_SYNC_START_DATE = '20100101'

/** 用于驱动交易日判断的交易所 */
export const TUSHARE_TRADE_CALENDAR_EXCHANGES = [StockExchange.SSE, StockExchange.SZSE] as const

/** 股票基础信息需覆盖全部上市状态，避免漏掉退市或暂停上市股票 */
export const TUSHARE_STOCK_LIST_STATUSES = [
  StockListStatus.LISTED,
  StockListStatus.DELISTED,
  StockListStatus.PAUSED,
] as const

/** 板块资金流向需要按类型分别同步 */
export const TUSHARE_MONEYFLOW_CONTENT_TYPES = [
  MoneyflowContentType.INDUSTRY,
  MoneyflowContentType.CONCEPT,
  MoneyflowContentType.REGION,
] as const

/** 资金流向仅保留最近 60 个交易日，避免在低积分账户下做不可持续的历史全量回补 */
export const TUSHARE_MONEYFLOW_RECENT_TRADE_DAYS = 60

/** 接口字段清单：字段来自 Tushare 文档镜像模型元数据 */
export const TUSHARE_STOCK_BASIC_FIELDS = [
  'ts_code',
  'symbol',
  'name',
  'area',
  'industry',
  'fullname',
  'enname',
  'cnspell',
  'market',
  'exchange',
  'curr_type',
  'list_status',
  'list_date',
  'delist_date',
  'is_hs',
  'act_name',
  'act_ent_type',
] as const

export const TUSHARE_STOCK_COMPANY_FIELDS = [
  'ts_code',
  'com_name',
  'com_id',
  'chairman',
  'manager',
  'secretary',
  'reg_capital',
  'setup_date',
  'province',
  'city',
  'introduction',
  'website',
  'email',
  'office',
  'ann_date',
  'business_scope',
  'employees',
  'main_business',
  'exchange',
] as const

export const TUSHARE_TRADE_CAL_FIELDS = ['exchange', 'cal_date', 'is_open', 'pretrade_date'] as const

export const TUSHARE_OHLCV_FIELDS = [
  'ts_code',
  'trade_date',
  'open',
  'high',
  'low',
  'close',
  'pre_close',
  'change',
  'pct_chg',
  'vol',
  'amount',
] as const

export const TUSHARE_ADJ_FACTOR_FIELDS = ['ts_code', 'trade_date', 'adj_factor'] as const

export const TUSHARE_DAILY_BASIC_FIELDS = [
  'ts_code',
  'trade_date',
  'close',
  'turnover_rate',
  'turnover_rate_f',
  'volume_ratio',
  'pe',
  'pe_ttm',
  'pb',
  'ps',
  'ps_ttm',
  'dv_ratio',
  'dv_ttm',
  'total_share',
  'float_share',
  'free_share',
  'total_mv',
  'circ_mv',
  'limit_status',
] as const

export const TUSHARE_MONEYFLOW_DC_FIELDS = [
  'ts_code',
  'trade_date',
  'buy_sm_vol',
  'buy_sm_amount',
  'sell_sm_vol',
  'sell_sm_amount',
  'buy_md_vol',
  'buy_md_amount',
  'sell_md_vol',
  'sell_md_amount',
  'buy_lg_vol',
  'buy_lg_amount',
  'sell_lg_vol',
  'sell_lg_amount',
  'buy_elg_vol',
  'buy_elg_amount',
  'sell_elg_vol',
  'sell_elg_amount',
  'net_mf_vol',
  'net_mf_amount',
] as const

export const TUSHARE_MONEYFLOW_IND_DC_FIELDS = [
  'trade_date',
  'content_type',
  'ts_code',
  'name',
  'pct_change',
  'close',
  'net_amount',
  'net_amount_rate',
  'buy_elg_amount',
  'buy_elg_amount_rate',
  'buy_lg_amount',
  'buy_lg_amount_rate',
  'buy_md_amount',
  'buy_md_amount_rate',
  'buy_sm_amount',
  'buy_sm_amount_rate',
  'buy_sm_amount_stock',
  'rank',
] as const

export const TUSHARE_MONEYFLOW_MKT_DC_FIELDS = [
  'trade_date',
  'close_sh',
  'pct_change_sh',
  'close_sz',
  'pct_change_sz',
  'net_amount',
  'net_amount_rate',
  'buy_elg_amount',
  'buy_elg_amount_rate',
  'buy_lg_amount',
  'buy_lg_amount_rate',
  'buy_md_amount',
  'buy_md_amount_rate',
  'buy_sm_amount',
  'buy_sm_amount_rate',
] as const

export const TUSHARE_INCOME_FIELDS = [
  'ts_code',
  'ann_date',
  'f_ann_date',
  'end_date',
  'report_type',
  'comp_type',
  'end_type',
  'basic_eps',
  'diluted_eps',
  'total_revenue',
  'revenue',
  'int_income',
  'prem_earned',
  'comm_income',
  'n_commis_income',
  'n_oth_income',
  'n_oth_b_income',
  'prem_income',
  'out_prem',
  'une_prem_reser',
  'reins_income',
  'n_sec_tb_income',
  'n_sec_uw_income',
  'n_asset_mg_income',
  'oth_b_income',
  'fv_value_chg_gain',
  'invest_income',
  'ass_invest_income',
  'forex_gain',
  'total_cogs',
  'oper_cost',
  'int_exp',
  'comm_exp',
  'biz_tax_surchg',
  'sell_exp',
  'admin_exp',
  'fin_exp',
  'assets_impair_loss',
  'prem_refund',
  'compens_payout',
  'reser_insur_liab',
  'div_payt',
  'reins_exp',
  'oper_exp',
  'compens_payout_refu',
  'insur_reser_refu',
  'reins_cost_refund',
  'other_bus_cost',
  'operate_profit',
  'non_oper_income',
  'non_oper_exp',
  'nca_disploss',
  'total_profit',
  'income_tax',
  'n_income',
  'n_income_attr_p',
  'minority_gain',
  'oth_compr_income',
  't_compr_income',
  'compr_inc_attr_p',
  'compr_inc_attr_m_s',
  'ebit',
  'ebitda',
  'insurance_exp',
  'undist_profit',
  'distable_profit',
  'rd_exp',
  'fin_exp_int_exp',
  'fin_exp_int_inc',
  'transfer_surplus_rese',
  'transfer_housing_imprest',
  'transfer_oth',
  'adj_lossgain',
  'withdra_legal_surplus',
  'withdra_legal_pubfund',
  'withdra_biz_devfund',
  'withdra_rese_fund',
  'withdra_oth_ersu',
  'workers_welfare',
  'distr_profit_shrhder',
  'prfshare_payable_dvd',
  'comshare_payable_dvd',
  'capit_comstock_div',
  'net_after_nr_lp_correct',
  'credit_impa_loss',
  'net_expo_hedging_benefits',
  'oth_impair_loss_assets',
  'total_opcost',
  'amodcost_fin_assets',
  'oth_income',
  'asset_disp_income',
  'continued_net_profit',
  'end_net_profit',
  'update_flag',
] as const

export const TUSHARE_BALANCE_SHEET_FIELDS = [
  'ts_code',
  'ann_date',
  'f_ann_date',
  'end_date',
  'report_type',
  'comp_type',
  'end_type',
  'total_share',
  'cap_rese',
  'undistr_porfit',
  'surplus_rese',
  'special_rese',
  'money_cap',
  'trad_asset',
  'notes_receiv',
  'accounts_receiv',
  'oth_receiv',
  'prepayment',
  'div_receiv',
  'int_receiv',
  'inventories',
  'amor_exp',
  'nca_within_1y',
  'sett_rsrv',
  'loanto_oth_bank_fi',
  'premium_receiv',
  'reinsur_receiv',
  'reinsur_res_receiv',
  'pur_resale_fa',
  'oth_cur_assets',
  'total_cur_assets',
  'fa_avail_for_sale',
  'htm_invest',
  'lt_eqt_invest',
  'invest_real_estate',
  'time_deposits',
  'oth_assets',
  'lt_rec',
  'fix_assets',
  'cip',
  'const_materials',
  'fixed_assets_disp',
  'produc_bio_assets',
  'oil_and_gas_assets',
  'intan_assets',
  'r_and_d',
  'goodwill',
  'lt_amor_exp',
  'defer_tax_assets',
  'decr_in_disbur',
  'oth_nca',
  'total_nca',
  'cash_reser_cb',
  'depos_in_oth_bfi',
  'prec_metals',
  'deriv_assets',
  'rr_reins_une_prem',
  'rr_reins_outstd_cla',
  'rr_reins_lins_liab',
  'rr_reins_lthins_liab',
  'refund_depos',
  'ph_pledge_loans',
  'refund_cap_depos',
  'indep_acct_assets',
  'client_depos',
  'client_prov',
  'transac_seat_fee',
  'invest_as_receiv',
  'total_assets',
  'lt_borr',
  'st_borr',
  'cb_borr',
  'depos_ib_deposits',
  'loan_oth_bank',
  'trading_fl',
  'notes_payable',
  'acct_payable',
  'adv_receipts',
  'sold_for_repur_fa',
  'comm_payable',
  'payroll_payable',
  'taxes_payable',
  'int_payable',
  'div_payable',
  'oth_payable',
  'acc_exp',
  'deferred_inc',
  'st_bonds_payable',
  'payable_to_reinsurer',
  'rsrv_insur_cont',
  'acting_trading_sec',
  'acting_uw_sec',
  'non_cur_liab_due_1y',
  'oth_cur_liab',
  'total_cur_liab',
  'bond_payable',
  'lt_payable',
  'specific_payables',
  'estimated_liab',
  'defer_tax_liab',
  'defer_inc_non_cur_liab',
  'oth_ncl',
  'total_ncl',
  'depos_oth_bfi',
  'deriv_liab',
  'depos',
  'agency_bus_liab',
  'oth_liab',
  'prem_receiv_adva',
  'depos_received',
  'ph_invest',
  'reser_une_prem',
  'reser_outstd_claims',
  'reser_lins_liab',
  'reser_lthins_liab',
  'indept_acc_liab',
  'pledge_borr',
  'indem_payable',
  'policy_div_payable',
  'total_liab',
  'treasury_share',
  'ordin_risk_reser',
  'forex_differ',
  'invest_loss_unconf',
  'minority_int',
  'total_hldr_eqy_exc_min_int',
  'total_hldr_eqy_inc_min_int',
  'total_liab_hldr_eqy',
  'lt_payroll_payable',
  'oth_comp_income',
  'oth_eqt_tools',
  'oth_eqt_tools_p_shr',
  'lending_funds',
  'acc_receivable',
  'st_fin_payable',
  'payables',
  'hfs_assets',
  'hfs_sales',
  'cost_fin_assets',
  'fair_value_fin_assets',
  'cip_total',
  'oth_pay_total',
  'long_pay_total',
  'debt_invest',
  'oth_debt_invest',
  'oth_eq_invest',
  'oth_illiq_fin_assets',
  'oth_eq_ppbond',
  'receiv_financing',
  'use_right_assets',
  'lease_liab',
  'contract_assets',
  'contract_liab',
  'accounts_receiv_bill',
  'accounts_pay',
  'oth_rcv_total',
  'fix_assets_total',
  'update_flag',
] as const

export const TUSHARE_CASHFLOW_FIELDS = [
  'ts_code',
  'ann_date',
  'f_ann_date',
  'end_date',
  'comp_type',
  'report_type',
  'end_type',
  'net_profit',
  'finan_exp',
  'c_fr_sale_sg',
  'recp_tax_rends',
  'n_depos_incr_fi',
  'n_incr_loans_cb',
  'n_inc_borr_oth_fi',
  'prem_fr_orig_contr',
  'n_incr_insured_dep',
  'n_reinsur_prem',
  'n_incr_disp_tfa',
  'ifc_cash_incr',
  'n_incr_disp_faas',
  'n_incr_loans_oth_bank',
  'n_cap_incr_repur',
  'c_fr_oth_operate_a',
  'c_inf_fr_operate_a',
  'c_paid_goods_s',
  'c_paid_to_for_empl',
  'c_paid_for_taxes',
  'n_incr_clt_loan_adv',
  'n_incr_dep_cbob',
  'c_pay_claims_orig_inco',
  'pay_handling_chrg',
  'pay_comm_insur_plcy',
  'oth_cash_pay_oper_act',
  'st_cash_out_act',
  'n_cashflow_act',
  'oth_recp_ral_inv_act',
  'c_disp_withdrwl_invest',
  'c_recp_return_invest',
  'n_recp_disp_fiolta',
  'n_recp_disp_sobu',
  'stot_inflows_inv_act',
  'c_pay_acq_const_fiolta',
  'c_paid_invest',
  'n_disp_subs_oth_biz',
  'oth_pay_ral_inv_act',
  'n_incr_pledge_loan',
  'stot_out_inv_act',
  'n_cashflow_inv_act',
  'c_recp_borrow',
  'proc_issue_bonds',
  'oth_cash_recp_ral_fnc_act',
  'stot_cash_in_fnc_act',
  'free_cashflow',
  'c_prepay_amt_borr',
  'c_pay_dist_dpcp_int_exp',
  'incl_dvd_profit_paid_sc_ms',
  'oth_cashpay_ral_fnc_act',
  'stot_cashout_fnc_act',
  'n_cash_flows_fnc_act',
  'eff_fx_flu_cash',
  'n_incr_cash_cash_equ',
  'c_cash_equ_beg_period',
  'c_cash_equ_end_period',
  'c_recp_cap_contrib',
  'incl_cash_rec_saims',
  'uncon_invest_loss',
  'prov_depr_assets',
  'depr_fa_coga_dpba',
  'amort_intang_assets',
  'lt_amort_deferred_exp',
  'decr_deferred_exp',
  'incr_acc_exp',
  'loss_disp_fiolta',
  'loss_scr_fa',
  'loss_fv_chg',
  'invest_loss',
  'decr_def_inc_tax_assets',
  'incr_def_inc_tax_liab',
  'decr_inventories',
  'decr_oper_payable',
  'incr_oper_payable',
  'others',
  'im_net_cashflow_oper_act',
  'conv_debt_into_cap',
  'conv_copbonds_due_within_1y',
  'fa_fnc_leases',
  'im_n_incr_cash_equ',
  'net_dism_capital_add',
  'net_cash_rece_sec',
  'credit_impa_loss',
  'use_right_asset_dep',
  'oth_loss_asset',
  'end_bal_cash',
  'beg_bal_cash',
  'end_bal_cash_equ',
  'beg_bal_cash_equ',
  'update_flag',
] as const

export const TUSHARE_EXPRESS_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'revenue',
  'operate_profit',
  'total_profit',
  'n_income',
  'total_assets',
  'total_hldr_eqy_exc_min_int',
  'diluted_eps',
  'diluted_roe',
  'yoy_net_profit',
  'bps',
  'yoy_sales',
  'yoy_op',
  'yoy_tp',
  'yoy_dedu_np',
  'yoy_eps',
  'yoy_roe',
  'growth_assets',
  'yoy_equity',
  'growth_bps',
  'or_last_year',
  'op_last_year',
  'tp_last_year',
  'np_last_year',
  'eps_last_year',
  'open_net_assets',
  'open_bps',
  'perf_summary',
  'is_audit',
  'remark',
  'update_flag',
] as const

export const TUSHARE_FINA_INDICATOR_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'eps',
  'dt_eps',
  'total_revenue_ps',
  'revenue_ps',
  'grossprofit_margin',
  'netprofit_margin',
  'roe',
  'roe_dt',
  'roa',
  'roic',
  'debt_to_assets',
  'current_ratio',
  'quick_ratio',
  'cash_ratio',
  'fcff',
  'fcfe',
  'ebit',
  'ebitda',
  'netdebt',
  'ocf_to_or',
  'or_yoy',
  'netprofit_yoy',
  'ocf_yoy',
  'dt_eps_yoy',
  'roe_yoy',
  'bps_yoy',
  'assets_yoy',
  'eqt_yoy',
  'tr_yoy',
] as const

export const TUSHARE_DIVIDEND_FIELDS = [
  'ts_code',
  'end_date',
  'ann_date',
  'div_proc',
  'stk_div',
  'stk_bo_rate',
  'stk_co_rate',
  'cash_div',
  'cash_div_tax',
  'record_date',
  'ex_date',
  'pay_date',
  'div_listdate',
  'imp_ann_date',
  'base_date',
  'base_share',
] as const

export const TUSHARE_TOP10_HOLDERS_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'holder_name',
  'hold_amount',
  'hold_ratio',
  'hold_float_ratio',
  'hold_change',
  'holder_type',
] as const

export const TUSHARE_TOP10_FLOAT_HOLDERS_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'holder_name',
  'hold_amount',
  'hold_ratio',
  'hold_float_ratio',
  'hold_change',
  'holder_type',
] as const

export const TUSHARE_INDEX_DAILY_FIELDS = [
  'ts_code',
  'trade_date',
  'close',
  'open',
  'high',
  'low',
  'pre_close',
  'change',
  'pct_chg',
  'vol',
  'amount',
] as const

export const TUSHARE_MONEYFLOW_HSGT_FIELDS = [
  'trade_date',
  'ggt_ss',
  'ggt_sz',
  'hgt',
  'sgt',
  'north_money',
  'south_money',
] as const

/** 需要同步的核心指数代码（共 19 个，涵盖沪深宽基、上交所、深交所、北交所主要指数） */
export const CORE_INDEX_CODES = [
  // 沪深宽基
  '000300.SH', // 沪深300
  '000016.SH', // 上证50
  '000903.SH', // 中证100
  '000905.SH', // 中证500
  '000852.SH', // 中证1000
  '932000.CSI', // 中证2000（CSI 后缀，需 Tushare 验证）
  '000985.SH', // 中证全指
  // 上交所
  '000001.SH', // 上证指数
  '000010.SH', // 上证180
  '000688.SH', // 科创50
  '000698.SH', // 科创100（需 Tushare 验证）
  // 深交所
  '399001.SZ', // 深证成指
  '399107.SZ', // 深证综指
  '399330.SZ', // 深证100
  '399006.SZ', // 创业板指
  '399673.SZ', // 创业板50
  '399005.SZ', // 中小100
  // 北交所
  '899050.BJ', // 北证50
] as const

export const TUSHARE_STK_LIMIT_FIELDS = ['ts_code', 'trade_date', 'up_limit', 'down_limit'] as const

export const TUSHARE_SUSPEND_D_FIELDS = ['ts_code', 'trade_date', 'suspend_timing', 'suspend_type'] as const

export const TUSHARE_INDEX_WEIGHT_FIELDS = ['index_code', 'con_code', 'trade_date', 'weight'] as const

/** 因子分析需要跟踪成分权重的核心指数 */
export const FACTOR_UNIVERSE_INDEX_CODES = [
  '000300.SH', // 沪深300
  '000905.SH', // 中证500
  '000852.SH', // 中证1000
  '000016.SH', // 上证50
] as const

export const TUSHARE_TOP_LIST_FIELDS = [
  'trade_date',
  'ts_code',
  'name',
  'close',
  'pct_change',
  'turnover_rate',
  'amount',
  'l_sell',
  'l_buy',
  'l_amount',
  'net_amount',
  'net_rate',
  'amount_rate',
  'float_values',
  'reason',
] as const

export const TUSHARE_TOP_INST_FIELDS = [
  'trade_date',
  'ts_code',
  'exalter',
  'buy',
  'buy_cost',
  'sell',
  'sell_cost',
  'net_buy',
  'side',
  'reason',
] as const

export const TUSHARE_BLOCK_TRADE_FIELDS = [
  'trade_date',
  'ts_code',
  'price',
  'vol',
  'amount',
  'buyer',
  'seller',
] as const

export const TUSHARE_SHARE_FLOAT_FIELDS = [
  'ts_code',
  'ann_date',
  'float_date',
  'float_share',
  'float_ratio',
  'holder_name',
  'share_type',
] as const

export const TUSHARE_FORECAST_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'type',
  'p_change_min',
  'p_change_max',
  'net_profit_min',
  'net_profit_max',
  'last_parent_net',
  'first_ann_date',
  'summary',
  'change_reason',
] as const

export const TUSHARE_STK_HOLDERNUMBER_FIELDS = ['ts_code', 'ann_date', 'end_date', 'holder_num'] as const

export const TUSHARE_HK_HOLD_FIELDS = ['code', 'trade_date', 'ts_code', 'name', 'vol', 'ratio', 'exchange'] as const

export const TUSHARE_INDEX_DAILYBASIC_FIELDS = [
  'ts_code',
  'trade_date',
  'total_mv',
  'float_mv',
  'total_share',
  'float_share',
  'free_share',
  'turnover_rate',
  'turnover_rate_f',
  'pe',
  'pe_ttm',
  'pb',
] as const

/** index_dailybasic 覆盖的 6 个核心大盘指数 */
export const INDEX_DAILY_BASIC_CODES = [
  '000001.SH', // 上证指数
  '399001.SZ', // 深证成指
  '000016.SH', // 上证50
  '000905.SH', // 中证500
  '399005.SZ', // 中小100
  '399006.SZ', // 创业板指
] as const

export const TUSHARE_STK_HOLDERTRADE_FIELDS = [
  'ts_code',
  'ann_date',
  'holder_name',
  'holder_type',
  'in_de',
  'change_vol',
  'change_ratio',
  'after_share',
  'after_ratio',
  'avg_price',
  'total_share',
  'begin_date',
  'close_date',
] as const

export const TUSHARE_PLEDGE_STAT_FIELDS = [
  'ts_code',
  'end_date',
  'pledge_count',
  'unrest_pledge',
  'rest_pledge',
  'total_share',
  'pledge_ratio',
] as const

export const TUSHARE_FINA_AUDIT_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'audit_result',
  'audit_fees',
  'audit_agency',
  'audit_sign',
] as const

export const TUSHARE_DISCLOSURE_DATE_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'pre_date',
  'actual_date',
  'modify_date',
] as const

export const TUSHARE_FINA_MAINBZ_FIELDS = [
  'ts_code',
  'end_date',
  'bz_item',
  'bz_sales',
  'bz_profit',
  'bz_cost',
  'curr_type',
  'update_flag',
] as const

export const TUSHARE_INDEX_CLASSIFY_FIELDS = [
  'index_code',
  'industry_name',
  'parent_code',
  'level',
  'industry_code',
  'is_pub',
  'src',
] as const

export const TUSHARE_INDEX_MEMBER_ALL_FIELDS = [
  'l1_code',
  'l1_name',
  'l2_code',
  'l2_name',
  'l3_code',
  'l3_name',
  'ts_code',
  'name',
  'in_date',
  'out_date',
  'is_new',
] as const

export const TUSHARE_REPURCHASE_FIELDS = [
  'ts_code',
  'ann_date',
  'end_date',
  'proc',
  'exp_date',
  'vol',
  'amount',
  'high_limit',
  'low_limit',
] as const

export const TUSHARE_CB_BASIC_FIELDS = [
  'ts_code',
  'bond_full_name',
  'bond_short_name',
  'cb_code',
  'stk_code',
  'stk_short_name',
  'maturity',
  'par',
  'issue_price',
  'issue_size',
  'remain_size',
  'value_date',
  'maturity_date',
  'rate_type',
  'coupon_rate',
  'add_rate',
  'pay_per_year',
  'list_date',
  'delist_date',
  'exchange',
  'conv_start_date',
  'conv_end_date',
  'conv_stop_date',
  'first_conv_price',
  'conv_price',
  'rate_clause',
  'put_clause',
  'maturity_put_price',
  'call_clause',
  'reset_clause',
  'conv_clause',
  'guarantor',
  'guarantee_type',
  'issue_rating',
  'newest_rating',
  'rating_comp',
] as const

export const TUSHARE_CB_DAILY_FIELDS = [
  'ts_code',
  'trade_date',
  'pre_close',
  'open',
  'high',
  'low',
  'close',
  'change',
  'pct_chg',
  'vol',
  'amount',
  'bond_value',
  'bond_over_rate',
  'cb_value',
  'cb_over_rate',
] as const
