ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_DISCLOSURE';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_FLOAT';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_DIVIDEND';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_FORECAST';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_IPO';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_CONVERTIBLE';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_SHAREHOLDER';
ALTER TYPE "price_alert_rule_type" ADD VALUE IF NOT EXISTS 'EVENT_ANY';
