import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import prettier from 'prettier'
import {
  AGENT_CAPABILITIES,
  AGENT_CONTRACT_JSON_SCHEMA,
  AGENT_ERROR_DEFINITIONS,
  AGENT_EVENT_FIXTURES,
  AGENT_EVENT_TYPES,
  AGENT_RUN_STATUSES,
  AGENT_STEP_STATUSES,
  AGENT_TOOL_KEYS,
  CONVERSATION_STATUSES,
  MESSAGE_BLOCK_FIXTURES,
  MESSAGE_ROLES,
  MESSAGE_STATUSES,
  MODEL_CALL_STATUSES,
  MODEL_POLICIES,
  TOOL_CALL_STATUSES,
} from 'src/apps/agent/contracts'

const backendSchemaPath = resolve('src/apps/agent/contracts/generated/agent-contracts.schema.json')
const frontendGeneratedPath = resolve('../client-code/src/types/agent/generated.ts')

function json(value: unknown): string {
  return JSON.stringify(value, null, 2)
}

export async function renderFrontendAgentContracts(): Promise<string> {
  const source = `
// AUTO-GENERATED by server-code/scripts/export-agent-contracts.ts. DO NOT EDIT.

export const CONVERSATION_STATUSES = ${json(CONVERSATION_STATUSES)} as const
export const MESSAGE_ROLES = ${json(MESSAGE_ROLES)} as const
export const MESSAGE_STATUSES = ${json(MESSAGE_STATUSES)} as const
export const AGENT_RUN_STATUSES = ${json(AGENT_RUN_STATUSES)} as const
export const AGENT_STEP_STATUSES = ${json(AGENT_STEP_STATUSES)} as const
export const TOOL_CALL_STATUSES = ${json(TOOL_CALL_STATUSES)} as const
export const MODEL_CALL_STATUSES = ${json(MODEL_CALL_STATUSES)} as const
export const MODEL_POLICIES = ${json(MODEL_POLICIES)} as const
export const AGENT_CAPABILITIES = ${json(AGENT_CAPABILITIES)} as const
export const AGENT_TOOL_KEYS = ${json(AGENT_TOOL_KEYS)} as const
export const AGENT_EVENT_TYPES = ${json(AGENT_EVENT_TYPES)} as const
export const AGENT_ERROR_DEFINITIONS = ${json(AGENT_ERROR_DEFINITIONS)} as const

export type ConversationStatus = (typeof CONVERSATION_STATUSES)[number]
export type MessageRole = (typeof MESSAGE_ROLES)[number]
export type MessageStatus = (typeof MESSAGE_STATUSES)[number]
export type AgentRunStatus = (typeof AGENT_RUN_STATUSES)[number]
export type AgentStepStatus = (typeof AGENT_STEP_STATUSES)[number]
export type ToolCallStatus = (typeof TOOL_CALL_STATUSES)[number]
export type ModelCallStatus = (typeof MODEL_CALL_STATUSES)[number]
export type ModelPolicy = (typeof MODEL_POLICIES)[number]
export type AgentCapability = (typeof AGENT_CAPABILITIES)[number]
export type AgentToolKey = (typeof AGENT_TOOL_KEYS)[number]
export type AgentEventType = (typeof AGENT_EVENT_TYPES)[number]
export type AgentErrorDefinition = (typeof AGENT_ERROR_DEFINITIONS)[number]

export type SourceType =
  | 'DATABASE'
  | 'PROGRAM_CALCULATION'
  | 'OFFICIAL'
  | 'MEDIA'
  | 'INSTITUTION'
  | 'MODEL_INFERENCE'
export type ValueScale = 'PERCENT' | 'DECIMAL'
export type PriceAdjustment = 'NONE' | 'FORWARD' | 'BACKWARD'

export type DataProvenance = {
  sourceType: SourceType
  citationIds: string[]
  asOf: {
    tradeDate?: string
    reportPeriod?: string
    announcementDate?: string
    availableAt?: string
    retrievedAt: string
  }
  timezone: string
  currency?: string
  unit?: string
  scale?: ValueScale
  adjustment?: PriceAdjustment
  dataVersion?: string
  algorithmVersion?: string
  qualityFlags?: string[]
}

export type BlockBase = {
  blockId: string
  schemaVersion: 1
  title?: string
  provenance?: DataProvenance
}
export type MarkdownBlock = BlockBase & { type: 'MARKDOWN'; text: string }
export type TableColumn = {
  key: string
  label: string
  valueType: 'STRING' | 'NUMBER' | 'DATE' | 'DATETIME' | 'BOOLEAN'
  unit?: string
  scale?: ValueScale
  align?: 'LEFT' | 'RIGHT' | 'CENTER'
}
export type TableCell = string | number | boolean | null
export type TableBlock = BlockBase & {
  type: 'TABLE'
  columns: TableColumn[]
  rows: Array<Record<string, TableCell>>
  rowKey: string
  truncated: boolean
  totalRows?: number
  provenance: DataProvenance
}
export type ChartPoint = { x: string | number; y: number | null }
export type ChartSeries = {
  key: string
  name: string
  points: ChartPoint[]
  unit?: string
  scale?: ValueScale
}
export type ChartBlock = BlockBase & {
  type: 'CHART'
  chart: 'LINE' | 'BAR' | 'AREA' | 'HEATMAP'
  xAxisType: 'CATEGORY' | 'DATETIME' | 'NUMBER'
  series: ChartSeries[]
  provenance: DataProvenance
}
export type KlineBar = {
  tradeDate: string
  open: number | null
  high: number | null
  low: number | null
  close: number | null
  volume: number | null
  amount: number | null
}
export type KlineBlock = BlockBase & {
  type: 'KLINE'
  tsCode: string
  frequency: 'DAILY' | 'WEEKLY' | 'MONTHLY'
  adjustment: PriceAdjustment
  priceUnit: string
  volumeUnit: string
  amountUnit: string
  bars: KlineBar[]
  provenance: DataProvenance
}
export type FinancialMetricValue = {
  key: string
  label: string
  value: number | null
  unit?: string
  scale?: ValueScale
}
export type FinancialMetricPeriod = {
  reportPeriod: string
  announcementDate?: string
  availableAt?: string
  reportType?: string
  metrics: FinancialMetricValue[]
}
export type FinancialMetricsBlock = BlockBase & {
  type: 'FINANCIAL_METRICS'
  tsCode: string
  periods: FinancialMetricPeriod[]
  provenance: DataProvenance
}
export type RiskNoticeBlock = BlockBase & {
  type: 'RISK_NOTICE'
  level: 'INFO' | 'WARNING' | 'CRITICAL'
  code: string
  text: string
  relatedBlockIds?: string[]
  provenance: DataProvenance
}
export type MessageBlock =
  | MarkdownBlock
  | TableBlock
  | ChartBlock
  | KlineBlock
  | FinancialMetricsBlock
  | RiskNoticeBlock

export type Citation = {
  citationId: string
  sourceId: string
  sourceType: SourceType
  title: string
  canonicalUrl?: string
  publisher?: string
  publishedAt?: string
  retrievedAt: string
  locator: {
    factId?: string
    section?: string
    paragraph?: number
    startOffset?: number
    endOffset?: number
  }
  contentHash: string
}

export type StreamError = {
  code: number
  message: string
  retryable: boolean
  category: 'VALIDATION' | 'AUTH' | 'MODEL' | 'TOOL' | 'SEARCH' | 'TIMEOUT' | 'INTERNAL'
  safeDetails?: Record<string, unknown>
}

export type AgentEventPayloadMap = {
  'message.created': { messageId: string; role: MessageRole; status: MessageStatus }
  'agent.started': { workflowKey: string; workflowVersion: number; modelPolicy: ModelPolicy }
  'agent.planning': { intent: string; capabilities: AgentCapability[]; planSummary: string }
  'agent.progress': { stepKey: string; label: string; completed: number; total: number | null }
  'tool.started': { toolCallId: string; toolName: AgentToolKey; inputSummary: string; attempt: number }
  'tool.completed': {
    toolCallId: string
    outputSummary: string
    rowCount: number
    truncated: boolean
    asOf: string
    citationIds: string[]
    durationMs: number
  }
  'tool.failed': { toolCallId: string; error: StreamError; attempt: number; willRetry: boolean }
  'model.started': { modelCallId: string; provider: string; model: string; purpose: string }
  'model.delta': { modelCallId: string; blockIndex: number; delta: string }
  'citation.created': { citation: Citation }
  'report.generated': { reportId: string; title: string; format: 'MARKDOWN' | 'PDF' }
  'agent.completed': {
    finalMessageId: string
    usage: { inputTokens: number; outputTokens: number; totalTokens: number }
    cost: { amount: number; currency: string }
    dataCutoff: string | null
    warnings: string[]
  }
  'agent.failed': { error: StreamError; failedStep: string | null; retryable: boolean }
  'agent.cancelled': { cancelledBy: 'USER' | 'SYSTEM' | 'TIMEOUT'; reason: string }
}

export type AgentEvent<TType extends AgentEventType> = {
  schemaVersion: '1.0'
  eventId: string
  sequence: number
  type: TType
  runId: string
  conversationId: string
  messageId?: string
  occurredAt: string
  traceId: string
  payload: AgentEventPayloadMap[TType]
}
export type AgentSseEvent = { [TType in AgentEventType]: AgentEvent<TType> }[AgentEventType]

type JsonSchema = Record<string, unknown>

export const AGENT_CONTRACT_JSON_SCHEMA = ${json(AGENT_CONTRACT_JSON_SCHEMA)} as const
export const AGENT_EVENT_FIXTURES = ${json(AGENT_EVENT_FIXTURES)} as unknown as AgentSseEvent[]
export const MESSAGE_BLOCK_FIXTURES = ${json(MESSAGE_BLOCK_FIXTURES)} as unknown as MessageBlock[]

export class AgentProtocolError extends Error {
  readonly code = 'AGENT_PROTOCOL_ERROR'

  constructor(readonly issues: string[]) {
    super(\`Agent 协议校验失败: \${issues.join('; ')}\`)
    this.name = AgentProtocolError.name
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function matchesType(type: string, value: unknown): boolean {
  if (type === 'null') return value === null
  if (type === 'object') return isRecord(value)
  if (type === 'array') return Array.isArray(value)
  if (type === 'string') return typeof value === 'string'
  if (type === 'number') return typeof value === 'number' && Number.isFinite(value)
  if (type === 'integer') return typeof value === 'number' && Number.isSafeInteger(value)
  if (type === 'boolean') return typeof value === 'boolean'
  return false
}

function validateNode(schema: JsonSchema, value: unknown, path: string, issues: string[]): void {
  if (Array.isArray(schema.oneOf)) {
    const matches = schema.oneOf.filter((candidate) => {
      const candidateIssues: string[] = []
      validateNode(candidate as JsonSchema, value, path, candidateIssues)
      return candidateIssues.length === 0
    })
    if (matches.length !== 1) issues.push(\`\${path} 必须且只能匹配一个 schema\`)
    return
  }
  if (Object.prototype.hasOwnProperty.call(schema, 'const') && value !== schema.const) {
    issues.push(\`\${path} const 不匹配\`)
    return
  }
  if (Array.isArray(schema.enum) && !schema.enum.includes(value)) {
    issues.push(\`\${path} 枚举不合法\`)
    return
  }
  if (schema.type) {
    const types = Array.isArray(schema.type) ? schema.type : [schema.type]
    if (!types.some((type) => matchesType(String(type), value))) {
      issues.push(\`\${path} 类型不合法\`)
      return
    }
  }
  if (typeof value === 'string') {
    if (typeof schema.minLength === 'number' && value.length < schema.minLength) issues.push(\`\${path} 太短\`)
    if (typeof schema.maxLength === 'number' && value.length > schema.maxLength) issues.push(\`\${path} 太长\`)
    if (typeof schema.pattern === 'string' && !new RegExp(schema.pattern).test(value)) issues.push(\`\${path} 格式不匹配\`)
    if (schema.format === 'date' && (!/^\\d{4}-\\d{2}-\\d{2}$/.test(value) || Number.isNaN(Date.parse(\`\${value}T00:00:00.000Z\`)))) issues.push(\`\${path} 日期不合法\`)
    if (schema.format === 'date-time' && Number.isNaN(Date.parse(value))) issues.push(\`\${path} 时间不合法\`)
  }
  if (typeof value === 'number') {
    if (typeof schema.minimum === 'number' && value < schema.minimum) issues.push(\`\${path} 小于最小值\`)
    if (typeof schema.maximum === 'number' && value > schema.maximum) issues.push(\`\${path} 超过最大值\`)
  }
  if (Array.isArray(value)) {
    if (typeof schema.minItems === 'number' && value.length < schema.minItems) issues.push(\`\${path} 元素不足\`)
    if (typeof schema.maxItems === 'number' && value.length > schema.maxItems) issues.push(\`\${path} 元素过多\`)
    if (isRecord(schema.items)) value.forEach((item, index) => validateNode(schema.items as JsonSchema, item, \`\${path}[\${index}]\`, issues))
  }
  if (isRecord(value)) {
    const properties = isRecord(schema.properties) ? schema.properties : {}
    const required = Array.isArray(schema.required) ? schema.required.map(String) : []
    required.forEach((key) => {
      if (!Object.prototype.hasOwnProperty.call(value, key)) issues.push(\`\${path}.\${key} 缺失\`)
    })
    Object.entries(value).forEach(([key, propertyValue]) => {
      const propertySchema = properties[key]
      if (isRecord(propertySchema)) validateNode(propertySchema, propertyValue, \`\${path}.\${key}\`, issues)
      else if (schema.additionalProperties === false) issues.push(\`\${path}.\${key} 不允许出现\`)
    })
  }
}

function assertSchema<T>(schema: JsonSchema, input: unknown, label: string): T {
  const issues: string[] = []
  validateNode(schema, input, label, issues)
  if (issues.length > 0) throw new AgentProtocolError(issues)
  return input as T
}

function schemaDefinition(name: 'AgentSseEvent' | 'MessageBlock'): JsonSchema {
  const definitions = AGENT_CONTRACT_JSON_SCHEMA.definitions as Record<string, JsonSchema>
  return definitions[name]
}

export function parseAgentSseEvent(input: unknown): AgentSseEvent {
  return assertSchema<AgentSseEvent>(schemaDefinition('AgentSseEvent'), input, 'AgentSseEvent')
}

export function parseMessageBlock(input: unknown): MessageBlock {
  const block = assertSchema<MessageBlock>(schemaDefinition('MessageBlock'), input, 'MessageBlock')
  if (block.type === 'MARKDOWN' && /<\\/?[A-Za-z][^>]*>/.test(block.text)) {
    throw new AgentProtocolError(['MessageBlock.text 禁止 raw HTML'])
  }
  return block
}

export function isSupportedMessageBlock(input: unknown): input is MessageBlock {
  try {
    parseMessageBlock(input)
    return true
  } catch {
    return false
  }
}
`

  const config = (await prettier.resolveConfig(frontendGeneratedPath)) ?? {}
  return prettier.format(source, { ...config, parser: 'typescript', filepath: frontendGeneratedPath })
}

function writeOrCheck(path: string, content: string, check: boolean): void {
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
      throw new Error(`Agent contract drift: ${path}`)
    }
    return
  }

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check')
  const schemaContent = `${json(AGENT_CONTRACT_JSON_SCHEMA)}\n`
  const frontendContent = await renderFrontendAgentContracts()

  writeOrCheck(backendSchemaPath, schemaContent, check)
  writeOrCheck(frontendGeneratedPath, frontendContent, check)
}

void main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
