#!/usr/bin/env sh
set -e

echo "[pre-push] generating swagger.json..."
pnpm swagger:generate

if ! git diff --quiet -- swagger.json; then
  echo "[pre-push] swagger.json has changed."
  echo "[pre-push] Please commit swagger.json before push."
  git add swagger.json
  exit 1
fi

echo "[pre-push] swagger.json is up to date."
